builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
        #  - arm
        #- arm64

    #goarm:
    #  - 7

    ldflags:
      - >-
        -s
        -w
        -X github.com/geaaru/pkgs-checker/cmd.BuildTime={{.Date}}
        -X github.com/geaaru/pkgs-checker/cmd.BuildCommit={{.Commit}}
        -X github.com/geaaru/pkgs-checker/cmd.BuildGoVersion={{.Env.GOVERSION}}

archives:
  - format: binary
    name_template: pkgs-checker-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Tag }}-source'
checksum:
  name_template: '{{ .ProjectName }}-{{ .Tag }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^scripts:'
      - '^contrib'
